name: Build & Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        env:
          - { CC: gcc-9, CXX: g++-9 }
          - { CC: clang-9, CXX: clang++-9 }

    runs-on: ubuntu-latest
    env: ${{ matrix.env }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Test
      run: pytest --verbose --capture=no
